import {
    Document,
    Page,
    Text,
    View,
    StyleSheet,
    Font,
  } from "@react-pdf/renderer";
  import type { MedicationAnalysisResponse } from "@/types/medication-analysis";
  
  // Register fonts (optional - for better typography)
  Font.register({
    family: "Inter",
    src: "https://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyfAZ9hiJ-Ek-_EeA.woff2",
  });
  
  const styles = StyleSheet.create({
    page: {
      padding: 40,
      fontFamily: "Inter",
      fontSize: 11,
      lineHeight: 1.5,
    },
    title: {
      fontSize: 24,
      fontWeight: "bold",
      marginBottom: 8,
      textAlign: "center",
    },
    subtitle: {
      fontSize: 12,
      color: "#666",
      marginBottom: 24,
      textAlign: "center",
    },
    sectionTitle: {
      fontSize: 16,
      fontWeight: "bold",
      marginTop: 20,
      marginBottom: 12,
      borderBottomWidth: 1,
      borderBottomColor: "#ddd",
      paddingBottom: 4,
    },
    medicationName: {
      fontSize: 14,
      fontWeight: "bold",
      marginTop: 12,
      marginBottom: 6,
    },
    bullet: {
      flexDirection: "row",
      marginBottom: 4,
      paddingLeft: 12,
    },
    bulletPoint: {
      width: 10,
    },
    bulletText: {
      flex: 1,
    },
    interactionBox: {
      backgroundColor: "#fff3cd",
      padding: 12,
      marginBottom: 12,
      borderRadius: 4,
    },
    interactionTitle: {
      fontWeight: "bold",
      marginBottom: 4,
    },
    adviceBox: {
      backgroundColor: "#d4edda",
      padding: 12,
      marginBottom: 8,
      borderRadius: 4,
    },
    disclaimer: {
      marginTop: 30,
      padding: 12,
      backgroundColor: "#f8f9fa",
      fontSize: 9,
      textAlign: "center",
      color: "#666",
    },
    safetyScore: {
      fontSize: 10,
      color: "#666",
      marginBottom: 4,
    },
  });
  
  interface MedicationReportPDFProps {
    data: MedicationAnalysisResponse;
    generatedAt?: Date;
  }
  
  export function MedicationReportPDF({ data, generatedAt = new Date() }: MedicationReportPDFProps) {
    return (
      <Document>
        <Page size="A4" style={styles.page}>
          {/* Header */}
          <Text style={styles.title}>Medication Interaction & Safety Report</Text>
          <Text style={styles.subtitle}>
            Generated by Cliniq Care • {generatedAt.toLocaleDateString()}
          </Text>
  
          {/* Summary of Individual Risks */}
          <Text style={styles.sectionTitle}>
            Summary of Individual Risks for Each Medication
          </Text>
          {data.individualResults.map((med, index) => (
            <View key={index}>
              <Text style={styles.medicationName}>
                {med.medicationName}
                {med.dosage && ` (${med.dosage}${med.measurement || "mg"})`}
              </Text>
              <Text style={styles.safetyScore}>
                Safety Score: {med.safetyScore ?? "N/A"}/100
              </Text>
              {med.warnings?.map((warning, i) => (
                <View key={i} style={styles.bullet}>
                  <Text style={styles.bulletPoint}>•</Text>
                  <Text style={styles.bulletText}>{warning}</Text>
                </View>
              ))}
            </View>
          ))}
  
          {/* Interactions Section */}
          {data.interactionAnalysis && data.interactionAnalysis.interactions.length > 0 && (
            <>
              <Text style={styles.sectionTitle}>
                Analysis of Potential Interactions Between Medications
              </Text>
              {data.interactionAnalysis.interactions.map((interaction, i) => (
                <View key={i} style={styles.interactionBox}>
                  <Text style={styles.interactionTitle}>Interaction {i + 1}</Text>
                  <Text>{interaction}</Text>
                </View>
              ))}
            </>
          )}
  
          {/* Recommendations/Advice */}
          <Text style={styles.sectionTitle}>
            Patient-Friendly Advice and Safety Recommendations
          </Text>
          {data.interactionAnalysis?.recommendations.map((rec, i) => (
            <View key={i} style={styles.adviceBox}>
              <Text>• {rec}</Text>
            </View>
          ))}
          {data.individualResults.flatMap((med) => med.recommendations || []).map((rec, i) => (
            <View key={`ind-${i}`} style={styles.adviceBox}>
              <Text>• {rec}</Text>
            </View>
          ))}
  
          {/* References */}
          <Text style={styles.sectionTitle}>References to Specific Warnings</Text>
          {data.individualResults.map((med, i) => (
            <View key={i} style={styles.bullet}>
              <Text style={styles.bulletPoint}>•</Text>
              <Text style={styles.bulletText}>
                <Text style={{ fontWeight: "bold" }}>{med.medicationName}:</Text>{" "}
                {med.warnings?.slice(0, 2).join(", ") || "No specific warnings"}
              </Text>
            </View>
          ))}
  
          {/* Disclaimer */}
          <View style={styles.disclaimer}>
            <Text>
              This report is not medical advice. Always consult your healthcare provider
              before making changes to your medication regimen.
            </Text>
          </View>
        </Page>
      </Document>
    );
  }