import "@/styles/globals.css";

import type { Metadata } from "next";
import { Geist } from "next/font/google";

import { PostHogProvider } from "@/components/PostHogProvider";
import { ThemeProvider } from "@/components/ThemeProvider";
import { TRPCReactProvider } from "@/trpc/react";
import { Toaster } from "sonner";

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	const isProduction = process.env.NODE_ENV === "production";

	return (
		<html lang="en" className={`${geist.variable}`} suppressHydrationWarning>
			<body>
				<ThemeProvider defaultTheme="system" storageKey="cliniq-theme">
					{isProduction ? (
						<PostHogProvider>
							<TRPCReactProvider>{children}</TRPCReactProvider>
						</PostHogProvider>
					) : (
						<TRPCReactProvider>{children}</TRPCReactProvider>
					)}
					<Toaster richColors position="top-center" />
				</ThemeProvider>
			</body>
		</html>
	);
}
