import {
	integer,
	jsonb,
	numeric,
	text,
	timestamp,
	uniqueIndex,
	uuid,
} from "drizzle-orm/pg-core";
import { createTable } from "../table";
import { user } from "./auth";
import { medications } from "./medications";
import { scans } from "./scans";

/**
 * Medication Deep-Dive table
 * Stores comprehensive, personalized medication information generated by AI
 */
export const medicationDeepDives = createTable(
	"medication_deep_dives",
	{
		id: uuid("id").primaryKey().defaultRandom(),
		userId: text("user_id")
			.references(() => user.id, { onDelete: "cascade" })
			.notNull(),
		medicationId: uuid("medication_id")
			.references(() => medications.id, { onDelete: "cascade" })
			.notNull(),
		scanId: uuid("scan_id").references(() => scans.id, {
			onDelete: "set null",
		}),

		// Caching & Versioning
		inputsHash: text("inputs_hash").notNull(),
		openfdaDataHash: text("openfda_data_hash"),

		// Structured output (JSONB for arrays and objects, text for strings)
		summary: text("summary"),
		whatItTreats: jsonb("what_it_treats"), // string[]
		howItWorks: text("how_it_works"),
		howToTake: jsonb("how_to_take"), // { timing, withFood, missedDose }
		expectedTimeline: text("expected_timeline"),
		benefits: jsonb("benefits"), // string[]
		sideEffects: jsonb("side_effects"), // { common: string[], serious: string[] }
		personalizedWarnings: jsonb("personalized_warnings"), // string[]
		interactions: jsonb("interactions"), // string[]
		lifestyle: jsonb("lifestyle"), // string[]
		monitoring: jsonb("monitoring"), // string[]
		questionsToAskDoctor: jsonb("questions_to_ask_doctor"), // string[]
		confidence: jsonb("confidence"), // { overall: "low"|"medium"|"high", reason: string }
		sourcesUsed: jsonb("sources_used"), // { scanLabel: bool, openFda: bool, patientProfile: bool }
		disclaimer: text("disclaimer"),

		// Metadata for monitoring and debugging
		rawLlmResponse: text("raw_llm_response"),
		aiModel: text("ai_model"),
		temperature: numeric("temperature"),
		tokensUsed: integer("tokens_used"),
		latencyMs: integer("latency_ms"),
		createdAt: timestamp("created_at").defaultNow(),
		updatedAt: timestamp("updated_at").defaultNow(),
	},
	(t) => ({
		// Unique index on inputs hash for fast cache lookups
		inputsHashUnique: uniqueIndex("medication_deep_dives_inputs_hash_idx").on(
			t.inputsHash,
		),
		// Unique constraint: only one deep-dive per user per medication
		userMedicationUnique: uniqueIndex(
			"medication_deep_dives_user_medication_idx",
		).on(t.userId, t.medicationId),
	}),
);
4