import { createTRPCRouter, protectedProcedure } from "@/server/api/trpc";
import { reports, userProfiles, user } from "@/server/db/schema";
import { desc, eq } from "drizzle-orm";
import { z } from "zod";
import { jsPDF } from "jspdf";
import type { MedicationAnalysisResponse } from "@/types/medication-analysis";

export const reportsRouter = createTRPCRouter({
	generateAllPDF: protectedProcedure.mutation(async ({ ctx }) => {
		const [profile] = await ctx.db
		.select({
			name: user.name,
			age: userProfiles.age,
		})
		.from(user)
		.leftJoin(userProfiles, eq(user.id, userProfiles.id))
		.where(eq(user.id, ctx.session.user.id))
		.limit(1);

		const allReports = await ctx.db
		  .select()
		  .from(reports)
		  .where(eq(reports.userId, ctx.session.user.id))
		  .orderBy(desc(reports.createdAt));
	  
		if (allReports.length === 0) {
		  throw new Error("No reports found");
		}
	  
		const doc = new jsPDF();
		let y = 20;
	  
		// Professional Color Scheme
		const colors: {
			primary: [number, number, number];
			secondary: [number, number, number];
			success: [number, number, number];
			warning: [number, number, number];
			danger: [number, number, number];
			lightBlue: [number, number, number];
			lightGreen: [number, number, number];
			lightOrange: [number, number, number];
			lightRed: [number, number, number];
			lightGray: [number, number, number];
			mediumGray: [number, number, number];
			textGray: [number, number, number];
			white: [number, number, number];
			black: [number, number, number];
		} = {
			primary: [41, 128, 185],
			secondary: [52, 73, 94],
			success: [39, 174, 96],
			warning: [243, 156, 18],
			danger: [231, 76, 60],
			lightBlue: [174, 214, 241],
			lightGreen: [213, 245, 227],
			lightOrange: [254, 235, 200],
			lightRed: [255, 235, 238],
			lightGray: [236, 240, 241],
			mediumGray: [189, 195, 199],
			textGray: [127, 140, 141],
			white: [255, 255, 255],
			black: [0, 0, 0],
		};
	  
		const checkPage = () => {
		  if (y > 270) { 
			doc.addPage(); 
			y = 20; 
		  }
		};

		const addBulletPoint = (text: string, indent: number = 20, bulletColor?: [number, number, number]) => {
			const lines = doc.splitTextToSize(text, 170 - indent);
			for (let i = 0; i < lines.length; i++) {
				checkPage();
				if (i === 0) {
					if (bulletColor) {
						doc.setTextColor(...bulletColor);
						doc.circle(indent + 1, y - 1, 1, 'F');
						doc.setTextColor(...colors.black);
						doc.text(" " + lines[i], indent + 3, y);
					} else {
						doc.text("• " + lines[i], indent, y);
					}
				} else {
					doc.text("  " + lines[i], indent + 3, y);
				}
				y += 5;
			}
		};

		const drawSectionDivider = () => {
			checkPage();
			doc.setDrawColor(...colors.mediumGray);
			doc.setLineWidth(0.5);
			doc.line(20, y, 190, y);
			y += 8;
		};

		const drawBox = (
			x: number,
			yPos: number,
			width: number,
			height: number,
			fillColor: [number, number, number],
			borderColor?: [number, number, number]
		) => {
			doc.setFillColor(...fillColor);
			if (borderColor) {
				doc.setDrawColor(...borderColor);
				doc.setLineWidth(0.5);
				doc.roundedRect(x, yPos, width, height, 2, 2, 'FD');
			} else {
				doc.roundedRect(x, yPos, width, height, 2, 2, 'F');
			}
		};

		
		// HEADER: Title with gradient-like effect
		const headerHeight = (profile?.name || profile?.age) ? 24 : 18;
		drawBox(20, y, 170, headerHeight, colors.primary);
		doc.setTextColor(...colors.white);
		doc.setFontSize(20);
		doc.setFont("helvetica", "bold");
		doc.text("Medication Interaction & Safety Report", 105, y + 8, { align: "center" });
		doc.setFontSize(9);
		doc.setFont("helvetica", "normal");
		doc.text("Generated by MediScan", 105, y + 14, { align: "center" });

		if (profile?.name || profile?.age) {
			let patientInfo = "Patient Name: ";
			if (profile.name) patientInfo += profile.name;
			else patientInfo += "No patient name available";
			if (profile.age) patientInfo += ` Age: ${profile.age}`;
			doc.setFontSize(10);
			doc.text(patientInfo, 105, y + 21, { align: "center" });
		}
		y += headerHeight + 4;
		
		// Date and info box
		drawBox(20, y, 170, 8, colors.lightGray);
		doc.setTextColor(...colors.textGray);
		doc.setFontSize(9);
		doc.text(`Report Date: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, 25, y + 5.5);
		doc.setTextColor(...colors.black);
		y += 12;
		
		// Collect all data from reports
		const allMedications: Array<{
			name: string;
			warnings: string[];
			recommendations: string[];
			interactions: string[];
		}> = [];
		
		let allInteractionAnalysis: any = null;
		
		for (const report of allReports) {
			const data = report.rawJson as MedicationAnalysisResponse;
			if (!data?.individualResults) continue;
			
			// Collect individual medications
			for (const med of data.individualResults) {
				allMedications.push({
					name: med.medicationName,
					warnings: med.warnings || [],
					recommendations: med.recommendations || [],
					interactions: med.interactions || []
				});
			}
			
			// Get interaction analysis (use the most recent one)
			if (data.interactionAnalysis && !allInteractionAnalysis) {
				allInteractionAnalysis = data.interactionAnalysis;
			}
		}
		
		// SECTION 1: Summary of Individual Risks for Each Medication
		checkPage();
		drawBox(20, y, 170, 10, colors.lightBlue);
		doc.setFontSize(14);
		doc.setFont("helvetica", "bold");
		doc.setTextColor(...colors.primary);
		doc.text("Summary of Individual Risks for Each Medication", 25, y + 7);
		doc.setTextColor(...colors.black);
		y += 14;
		
		for (const med of allMedications) {
			checkPage();
			
			// Medication name with accent bar
			// doc.setDrawColor(...colors.danger);
			// doc.setLineWidth(3);
			// doc.line(20, y - 2, 20, y + 4);
			
			doc.setFontSize(12);
			doc.setFont("helvetica", "bold");
			doc.setTextColor(...colors.secondary);
			doc.text(med.name, 26, y + 2);
			doc.setTextColor(...colors.black);
			y += 7;
			
			// Warnings with red bullets
			doc.setFontSize(10);
			doc.setFont("helvetica", "normal");
			
			if (med.warnings.length > 0) {
				for (const warning of med.warnings) {
					addBulletPoint(warning, 30);
				}
			} else {
				doc.setTextColor(...colors.textGray);
				doc.text("No specific warnings identified.", 26, y);
				doc.setTextColor(...colors.black);
				y += 5;
			}
			
			y += 6;
		}
		
		drawSectionDivider();
		
		// SECTION 2: Analysis of Potential Interactions Between Medications
		if (allInteractionAnalysis && allInteractionAnalysis.interactions?.length > 0) {
			checkPage();
			
			drawBox(20, y, 170, 10, colors.lightOrange);
			doc.setFontSize(14);
			doc.setFont("helvetica", "bold");
			doc.setTextColor(...colors.warning);
			doc.text("Analysis of Potential Interactions Between Medications", 25, y + 7);
			doc.setTextColor(...colors.black);
			y += 14;
			
			// Subsection header
			doc.setFontSize(12);
			doc.setFont("helvetica", "bold");
			doc.setTextColor(...colors.secondary);
			doc.text("Interactions", 20, y);
			doc.setTextColor(...colors.black);
			y += 8;
			
			// List each interaction in styled boxes
			for (let i = 0; i < allInteractionAnalysis.interactions.length; i++) {
				const interaction = allInteractionAnalysis.interactions[i];
				checkPage();
				
				// Parse interaction
				let title = "";
				let description = "";
				let example = "";
				
				if (interaction.includes('\n')) {
					const parts = interaction.split('\n');
					title = parts[0] || "";
					description = parts.slice(1).join(' ').trim();
				} else {
					const sentences = interaction.split('. ');
					if (sentences.length > 1) {
						title = sentences[0];
						description = sentences.slice(1).join('. ');
					} else {
						title = "Interaction Risk";
						description = interaction;
					}
				}
				
				if (description.toLowerCase().includes('example:')) {
					const exampleParts = description.split(/example:/i);
					description = exampleParts[0]?.trim() || "";
					example = exampleParts[1]?.trim() || "";
				}
				
				// Calculate box height
				const titleLines = doc.splitTextToSize(title, 160);
				const descLines = doc.splitTextToSize(description, 160);
				const exampleLines = example ? doc.splitTextToSize(`Example: ${example}`, 160) : [];
				const boxHeight = (titleLines.length * 5.5) + (descLines.length * 5) + (exampleLines.length * 5) + 10;
				
				// Draw interaction box
				drawBox(20, y, 170, boxHeight, colors.lightOrange, colors.warning);
				
				const boxStartY = y;
				y += 5;
				
				// Render title
				doc.setFontSize(11);
				doc.setFont("helvetica", "bold");
				doc.setTextColor(...colors.warning);
				for (const line of titleLines) {
					checkPage();
					doc.text(line, 25, y);
					y += 5.5;
				}
				
				// Render description
				doc.setFontSize(10);
				doc.setFont("helvetica", "normal");
				doc.setTextColor(...colors.black);
				for (const line of descLines) {
					checkPage();
					doc.text(line, 25, y);
					y += 5;
				}
				
				// Render example
				if (example) {
					y += 1;
					doc.setFont("helvetica", "italic");
					doc.setTextColor(...colors.textGray);
					const exampleText = `Example: ${example}`;
					const exLines = doc.splitTextToSize(exampleText, 160);
					for (const line of exLines) {
						checkPage();
						doc.text(line, 25, y);
						y += 5;
					}
					doc.setTextColor(...colors.black);
				}
				
				y = boxStartY + boxHeight + 5;
			}
			
			drawSectionDivider();
		}
		
		// SECTION 3: Patient-Friendly Advice and General Safety Recommendations
		checkPage();
		drawBox(20, y, 170, 10, colors.lightGreen);
		doc.setFontSize(14);
		doc.setFont("helvetica", "bold");
		doc.setTextColor(...colors.success);
		doc.text("Patient-Friendly Advice and General Safety Recommendations", 25, y + 7);
		doc.setTextColor(...colors.black);
		y += 14;
		
		doc.setFontSize(12);
		doc.setFont("helvetica", "bold");
		doc.setTextColor(...colors.secondary);
		doc.text("Advice", 20, y);
		doc.setTextColor(...colors.black);
		y += 8;
		
		// Collect all recommendations
		const allRecommendations: string[] = [];
		
		for (const med of allMedications) {
			if (med.recommendations.length > 0) {
				allRecommendations.push(...med.recommendations);
			}
		}
		
		if (allInteractionAnalysis?.recommendations) {
			allRecommendations.push(...allInteractionAnalysis.recommendations);
		}
		
		// Display recommendations with green bullets
		doc.setFontSize(10);
		doc.setFont("helvetica", "normal");
		
		if (allRecommendations.length > 0) {
			for (const rec of allRecommendations) {
				addBulletPoint(rec, 25);
			}
		} else {
			doc.setTextColor(...colors.textGray);
			doc.text("No specific recommendations at this time.", 20, y);
			doc.setTextColor(...colors.black);
			y += 5;
		}
		
		drawSectionDivider();
		
		// SECTION 4: References to Specific Warnings Provided
		checkPage();
		drawBox(20, y, 170, 10, colors.lightGray);
		doc.setFontSize(14);
		doc.setFont("helvetica", "bold");
		doc.setTextColor(...colors.secondary);
		doc.text("References to Specific Warnings Provided", 25, y + 7);
		doc.setTextColor(...colors.black);
		y += 14;
		
		doc.setFontSize(12);
		doc.setFont("helvetica", "bold");
		doc.text("References", 20, y);
		y += 8;
		
		// List each medication with warnings summary
		doc.setFontSize(10);
		doc.setFont("helvetica", "normal");
		
		for (const med of allMedications) {
			checkPage();
			
			// Medication name in bold
			doc.setFont("helvetica", "bold");
			doc.setTextColor(...colors.primary);
			doc.text("• " + med.name + ":", 25, y);
			doc.setFont("helvetica", "normal");
			doc.setTextColor(...colors.black);
			y += 5;
			
			// Warnings as sub-bullets
			if (med.warnings.length > 0) {
				for (const warning of med.warnings) {
					const lines = doc.splitTextToSize("- " + warning, 145);
					for (const line of lines) {
						checkPage();
						doc.text(line, 35, y);
						y += 5;
					}
				}
			}
			else {
				doc.setTextColor(...colors.textGray);
				doc.text("- No specific warnings", 35, y);
				doc.setTextColor(...colors.black);
				y += 5;
			}
			
			y += 3;
		}
		
		y += 8;
		
		// FOOTER: Disclaimer with border
		checkPage();
		drawBox(20, y, 170, 15, colors.lightRed, colors.danger);
		doc.setFontSize(9);
		doc.setTextColor(...colors.danger);
		doc.setFont("helvetica", "bold");
		doc.text("IMPORTANT MEDICAL DISCLAIMER", 105, y + 5, { align: "center" });
		doc.setFont("helvetica", "normal");
		doc.setTextColor(...colors.textGray);
		doc.setFontSize(8);
		const disclaimerText = "This report is not medical advice. Always consult your healthcare provider before making any changes to your medication regimen or if you have questions about drug interactions.";
		const disclaimerLines = doc.splitTextToSize(disclaimerText, 165);
		doc.text(disclaimerLines, 22.5, y + 9);
	  
		return {
		  filename: `medication-report-${Date.now()}.pdf`,
		  data: doc.output("datauristring").split(",")[1]!,
		};
    }),
    
	getAll: protectedProcedure.query(async ({ ctx }) => {
		return ctx.db
		  .select()
		  .from(reports)
		  .where(eq(reports.userId, ctx.session.user.id))
		  .orderBy(desc(reports.createdAt));
	}),

   delete: protectedProcedure
    .input(z.object({ id: z.string() }))
    .mutation(async ({ ctx, input }) => {
      const [report] = await ctx.db
        .select()
        .from(reports)
        .where(eq(reports.id, input.id))
        .limit(1);
      if (!report || report.userId !== ctx.session.user.id) {
        throw new Error("Not found");
      }
      await ctx.db.delete(reports).where(eq(reports.id, input.id));
      return { success: true };
    }),
});
